### ISSUE TITLE
Constraints Causing Display Issue (Xcode 8)

### ISSUE THREAD

**Issue by po7h3ad** [kentya6/KYCircularProgress#16]
I've run into an issue in xcode 8 where applying constraints or using autoresizing on the KYCircularProgress view causes the progress bar to display in unexpected ways.

Positioning constraints appear to affect the guide line, causing it to no longer display (or be moved outside of the view). Any constraints relating to the size of the view (width, height etc.) cause the progress line to be massively enlarged.

The views frame appears to react correctly to the constraints, it is just the graphic that is affected. Setting the constraints programmatically has the same effect. 

Setting the constraints and saving the storyboard for xcode 7 fixes the issues. This works fine as a workaround

**No Constraints**

![simulator screen shot 24 oct 2016 12 55 32 pm](https://cloud.githubusercontent.com/assets/5839851/19643603/649cd660-99eb-11e6-98e6-307b7cc89244.png)

**Positioning Constraints**

![positioning](https://cloud.githubusercontent.com/assets/5839851/19643720/f44b4fa8-99eb-11e6-8f76-bb948d34a880.jpg)

**Size Constraints**

![sizing](https://cloud.githubusercontent.com/assets/5839851/19643622/75a78e00-99eb-11e6-9432-38235b35be78.jpg)

**Comment by maxgorodivskyi** [comment]
I encountered same issue. It's caused by calling configureProgressLayer() when view isn't played out and frame is some nonsense like (0, 0, 1000, 1000). Similar issue [http://stackoverflow.com/questions/39578530/since-xcode-8-and-ios10-views-are-not-sized-properly-on-viewdidlayoutsubviews](url)
It can be possibly cured by overriding layoutSubviews() and changing progress layer bounds.
Also I've found that when using autoresizing masks view works as expected so it can be used as temporary workaround.

**Comment by kentya6** [comment]
Hi, @po7h3ad, @maxgorodivskyi

Thanks for your issuing.
I've been updated library to [1.0.0](https://github.com/kentya6/KYCircularProgress/releases/tag/1.0.0).
This major update is added various features, and redesigned according to [design guidelines](https://swift.org/documentation/api-design-guidelines/). And Xcode 8 layout issue is also fixed.

Thanks.
